#!/bin/bash
# How to use: wget -qO- CLITools.tk/install-speedtest | bash
# or wget -qO- speedtestcli.tk | bash

cd ~
res1=$(date +%s.%N)



echo
echo
echo Name:		Speedtest Installer
echo Version:	0.0.2 - Stable
echo Date:		30.06.2020
echo Author:	TechHome/marrobhd
echo Source:	info.clitools.tk
echo
echo


echo Installation has been started
echo ----------------------------------------------------------

# Script only works if sudo caches the password for a few minutes
sudo true

if DISTRIBUTER=$(lsb_release -si); then
    echo
    echo
else
    echo Trying to fix errors...
    sudo yum install redhat-lsb-core -y
    apt-get install lsb-release -y
    DISTRIBUTER=$(lsb_release -si)
fi

export DEB_DISTRO=$(lsb_release -sc)
echo $DEB_DISTRO
echo $DISTRIBUTER

if [ "$DISTRIBUTER" == "Ubuntu" ]; then
    echo $DISTRIBUTER
    export DEB_DISTRO=bionic
    sudo apt-get install gnupg1 apt-transport-https dirmngr -y
    export INSTALL_KEY=379CE192D401AB61
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY
    echo "deb https://ookla.bintray.com/debian ${DEB_DISTRO} main" | sudo tee  /etc/apt/sources.list.d/speedtest.list
    sudo apt-get update
    # Other non-official binaries will conflict with Speedtest CLI
    # Example how to remove using apt-get
    # sudo apt-get remove speedtest-cli
    sudo apt-get install speedtest -y
elif [ "$DISTRIBUTER" == "Debian" ]; then
    echo $DISTRIBUTER
    apt-get install gnupg1 apt-transport-https dirmngr -y
    export INSTALL_KEY=379CE192D401AB61
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY
    echo "deb https://ookla.bintray.com/debian ${DEB_DISTRO} main" | sudo tee  /etc/apt/sources.list.d/speedtest.list
    apt-get update
    # Other non-official binaries will conflict with Speedtest CLI
    # Example how to remove using apt-get
    # sudo apt-get remove speedtest-cli
    apt-get install speedtest -y
elif [ "$DISTRIBUTER" == "Fedora" ] || [ "$DISTRIBUTER" == "CentOS" ]; then
    echo $DISTRIBUTER
    sudo yum install wget -y
    wget https://bintray.com/ookla/rhel/rpm -O bintray-ookla-rhel.repo
    sudo mv bintray-ookla-rhel.repo /etc/yum.repos.d/
    # Other non-official binaries will conflict with Speedtest CLI
    # Example how to remove using yum
    # rpm -qa | grep speedtest | xargs -I {} sudo yum -y remove {}
    sudo yum install speedtest -y
    exit
fi


echo
echo ----------------------------------------------------------
echo Finished!
res2=$(date +%s.%N)
dt=$(echo "$res2 - $res1" | bc)
dd=$(echo "$dt/86400" | bc)
dt2=$(echo "$dt-86400*$dd" | bc)
dh=$(echo "$dt2/3600" | bc)
dt3=$(echo "$dt2-3600*$dh" | bc)
dm=$(echo "$dt3/60" | bc)
ds=$(echo "$dt3-60*$dm" | bc)
LC_NUMERIC=C printf "Total runtime: %d:%02d:%02d:%02.4f\n" $dd $dh $dm $ds
echo
