#!/bin/bash
# How to use:
# Linux:
# wget -qO- CLITools.tk/install-speedtest-lnx | bash


echo ""
echo ""
echo "Name:		Speedtest.net CLI Installer Linux"
echo "Version:	0.0.4 - Stable"
echo "Date:		23.04.2021"
echo "Author:	TechHome/marrobhd"
echo "Source:	info.clitools.tk"
echo ""
echo ""


echo "Installation has been started"
echo "----------------------------------------------------------"

# Bash code
# --------------------
cd ~
res1=$(date +%s.%N)

# Script only works if sudo caches the password for a few minutes
sudo true

if DISTRIBUTER=$(lsb_release -si); then
    echo
    echo
else
    echo Trying to fix errors...
    sudo yum install redhat-lsb-core -y
    zypper install -y lsb-release
    apt-get install lsb-release -y
    DISTRIBUTER=$(lsb_release -si)
	  OS=$(lsb_release -sd)
	  echo "Operating-System: $OS"
fi

export DEB_DISTRO=$(lsb_release -sc)
echo $DEB_DISTRO
echo $DISTRIBUTER

if [ "$DISTRIBUTER" == "Ubuntu" ]; then
    echo $DISTRIBUTER
    export DEB_DISTRO=bionic
    #sudo apt-get install gnupg1 apt-transport-https dirmngr bc -y
    curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
    # Other non-official binaries will conflict with Speedtest CLI
    # Example how to remove using apt-get
    sudo apt-get remove speedtest-cli
    sudo apt-get install speedtest -y
elif [ "$DISTRIBUTER" == "Debian" ]; then
    echo $DISTRIBUTER
    #apt-get install gnupg1 apt-transport-https dirmngr bc -y
    curl -s https://install.speedtest.net/app/cli/install.deb.sh | bash
    # Other non-official binaries will conflict with Speedtest CLI
    # Example how to remove using apt-get
    apt-get remove speedtest-cli
    apt-get install speedtest -y
elif [ "$DISTRIBUTER" == "openSUSE" ]; then
    echo $DISTRIBUTER
    zypper install -y speedtest-cli bc
elif [ "$DISTRIBUTER" == "Fedora" ] || [ "$DISTRIBUTER" == "CentOS" ]; then
    echo $DISTRIBUTER
    #sudo yum install wget bc -y
    #wget https://bintray.com/ookla/rhel/rpm -O bintray-ookla-rhel.repo
    #sudo mv bintray-ookla-rhel.repo /etc/yum.repos.d/
    # Other non-official binaries will conflict with Speedtest CLI
    # Example how to remove using yum
    # rpm -qa | grep speedtest | xargs -I {} sudo yum -y remove {}
    curl -s https://install.speedtest.net/app/cli/install.rpm.sh | sudo bash
    sudo yum install speedtest -y
    exit
elif true; then
    echo $DISTRIBUTER
    sudo pkg update && sudo pkg install -g libidn2 ca_root_nss
    # Example how to remove conflicting or old versions using pkg
    # sudo pkg remove speedtest
    sudo pkg add "https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-freebsd.pkg"
    exit
fi


echo
echo ----------------------------------------------------------
echo Installed! Just run 'speedtest'
res2=$(date +%s.%N)
dt=$(echo "$res2 - $res1" | bc)
dd=$(echo "$dt/86400" | bc)
dt2=$(echo "$dt-86400*$dd" | bc)
dh=$(echo "$dt2/3600" | bc)
dt3=$(echo "$dt2-3600*$dh" | bc)
dm=$(echo "$dt3/60" | bc)
ds=$(echo "$dt3-60*$dm" | bc)
LC_NUMERIC=C printf "Total runtime: %d:%02d:%02d:%02.4f\n" $dd $dh $dm $ds
echo
