#!/bin/bash
# How to use: wget -qO- CLITools.tk/install-speedtest>install-speedtest && chmod +x install-speedtest && ./install-speedtest)

cd ~
res1=$(date +%s.%N)



echo
echo
echo Name:		Speedtest Installer
echo Version:	0.0.1 - Stable
echo Date:		29.06.2020
echo Author:	TechHome/marrobhd
echo Source:	info.clitools.tk
echo
echo


echo Installation has been started
echo ----------------------------------------------------------

UBUNTU=$(lsb_release -si)

apt-get install sudo
sudo apt-get install gnupg1 apt-transport-https dirmngr -y
export INSTALL_KEY=379CE192D401AB61
# Ubuntu versions supported: xenial, bionic
# Debian versions supported: jessie, stretch, buster

export DEB_DISTRO=$(lsb_release -sc)

if [ "$UBUNTU" == "Ubuntu" ]; then
    export DEB_DISTRO=bionic
fi

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY
echo "deb https://ookla.bintray.com/debian ${DEB_DISTRO} main" | sudo tee  /etc/apt/sources.list.d/speedtest.list
sudo apt-get update
# Other non-official binaries will conflict with Speedtest CLI
# Example how to remove using apt-get
# sudo apt-get remove speedtest-cli
sudo apt-get install speedtest


echo
echo ----------------------------------------------------------
echo Finished!
res2=$(date +%s.%N)
dt=$(echo "$res2 - $res1" | bc)
dd=$(echo "$dt/86400" | bc)
dt2=$(echo "$dt-86400*$dd" | bc)
dh=$(echo "$dt2/3600" | bc)
dt3=$(echo "$dt2-3600*$dh" | bc)
dm=$(echo "$dt3/60" | bc)
ds=$(echo "$dt3-60*$dm" | bc)
LC_NUMERIC=C printf "Total runtime: %d:%02d:%02d:%02.4f\n" $dd $dh $dm $ds
echo
